FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
# Copie todo o código para dentro do contêiner
COPY . .

# Copie o arquivo .env, se necessário
COPY .env .env

# Exponha a porta 5000 (ou a porta em que seu aplicativo Node.js está configurado para rodar)
EXPOSE 5000

RUN npm run build

# Comando para rodar o aplicativo Node.js
CMD ["node", "dist/index.js"]